### ISSUE TITLE
Player.guild returns null

### ISSUE THREAD

**Issue by despenser08** [Hypixel-API-Reborn/hypixel-api-reborn#134]
`Client.getPlayer("name").guild` should return `Guild`; but code always return null.

**Comment by muchnameless** [comment]
The player endpoint doesn't provide any information about the guild, so in order to get that data the lib does an extra API call to the guild endpoint, **if** the fetchoptions include `{ guild: true }`.
Use `getPlayer('name', { guild: true })` and if `<Player>.guild` is `null` it means they are not in any guild.

**Comment by muchnameless** [comment]
just noticed that this is missing from the jsdoc example, will PR a fix

**Comment by SamHoque** [comment]
This is still returning `null` even after passing the guild variable.
